name: 'test'

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn

      - name: Connect to VPN
        uses: ./
        with:
          ovpnConfig: ${{ secrets.OVPN_CONFIG }}
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
